[project]
name = "sier2-examples"
version = "0.13.3"
description = "Example sier2 block library"
readme = "README.md"
#authors = [
#    {name="Example author", email="author@example.com"}
#]
requires-python = ">=3.12"
dependencies = [
    "sier2>=0.8.0"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["sier2_examples"]

[project.entry-points."sier2.library"]
export = "sier2_examples:shelf"
